### ISSUE TITLE
Untar/unzip + /usr/bin vs /usr/local/bin

### ISSUE THREAD

**Issue by corbin-zip** [PrabuddhMathur/enchiridion-robin-homer-git#1]
Hello and thank you for this application! I randomly searched for "stoic" on the AUR and was pleasantly surprised. I actually wrote [a very similar script](https://old.reddit.com/r/Stoicism/comments/4bz797/practical_stoicism/j3j5us1/?context=3) about 3 months ago, but it relies on a PDF (available in the linked thread as well, if you're curious)

Anyhow, I'm no "git guru" or anything, but I think it's generally preferred to at least have your bash script outside of the archive, however I think it'd be best to just remove the archive entirely and put the audio files in their own directory. Since this is on the AUR and the onus is on the user (ie: me) to verify that the application is safe to run, it necessitates that the user clones the repo and extracts the archive to inspect its contents which is trivial but time-consuming. It's probably best to take the archive out of the equation, removing the need to clone the repo since the user can now simply look at its contents on github, if that makes sense

Now that I've verified its contents, I look forward to using it, but I figured it was worth the suggestion!

Additionally, this may be more a pedantic suggestion, but I _think_ that this should be getting installed to /usr/bin instead of /usr/local/bin. My understanding is that the local directory is for packages that are not managed at all by a package manager, while AUR packages [are technically still managed by pacman](https://wiki.archlinux.org/title/Makepkg) (and that seems to be the purpose of this repo, after all)

If you don't have the time to make these changes, I've never submitted a pull request on github before but I wouldn't mind trying to figure it out and making this my first

Thanks again!

Corbin

**Comment by PrabuddhMathur** [comment]
Hey Corbin! 

I'm well aware of these issues with the archive in the git repository and the installation of the script in /usr/bin rather than /usr/local/bin. I made this script a package earlier in January, not too surprising, that this is my first ever AUR package so I had to do many changes to make this work. This was the first version, after many trials and errors with Makefile configuration, that was working. So I didn't tinker with it much and let it be for the time being. After that I got busy with my University studies and was able to give this time. 
I'd love if you could solve these issues in the pull request. I'm not much of a Git Guru myself as well, but I'll look into it and merge your request! It'd be a great help!

Edit: I'm quite thrilled to get to know a fellow Linux user who is also a Stoic. I must say that this combo is quite difficult to find. Looking forward to collaborate with you!

Prabuddh

**Comment by corbin-zip** [comment]
Hi Prabuddh

Very nice to meet you as well! I went ahead and submitted the PR; I hope I did it all correctly. I tried to test it as best as I could, but there may be some "best practices" that I'm not aware of, or maybe a bug that I missed. Anyhow, I would consider this issue closed so I'll go ahead and do exactly that

I think I'm a better Linux user than I am a Stoic but it's probably best to just say I'm a student of both, haha. Feel free to reach out if you have any future ideas or plans for Stoic-related projects, as I would likely be interested in helping in some capacity!

Corbin
